#pragma once
#include <string>

const std::string FOUNDATION_PRIVKEY =
    R"(-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgZ1GiMjKav7X7bwEf3iGk
ohXdoJ+zQhcUXra153Ma1iuhRANCAARuok1M95cc52opukVnBaMPJqeQdXH9MQ62
7Z4y2FLAEIcgfHReKJKjcm/LHZf8OdA6z1TdM2XbJBCbB8FoyUax
-----END PRIVATE KEY-----
)";

